language: php
php:
  - 5.6
  - 5.5
  - 5.4
  - 5.3
  - hhvm
matrix:
  allow_failures:
    - php: [hhvm, 5.3, 5.4]
install:
  - composer install
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --format=php-clover tests/_output/coverage.clover
script: vendor/codeception/codeception/codecept --colors --coverage-xml=coverage.clover --coverage-html=. run