language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm
matrix:
  allow_failures:
    - php: nightly
cache:
  directories:
    - vendor
install:
  - composer install --dev --prefer-dist
  - rm -rf vendor/maslosoft/embeditest
  - git clone https://github.com/Maslosoft/EmbediTest.git vendor/maslosoft/embeditest
before_script:
  - cd $TRAVIS_BUILD_DIR
script:
  - bash run-travis
