language: php
php:
  - 5.6
  - 5.5
  - 5.4
install:
  - composer install --dev --prefer-source
after_script:
  - wget https://scrutinizer-ci.com/ocular.phar
  - php ocular.phar code-coverage:upload --repository=g/Maslosoft/EmbeDi --revision=`git rev-parse HEAD` --format=php-clover ./tests/_output/coverage.clover
script: vendor/bin/codecept run unit --coverage --html --coverage-html=. --coverage-xml=./coverage.clover